%Your Implementation of Newton's method
%INPUTS:
%fun: the mathematical function for which we want to compute the root
%   note that the output of fun may include the derivative
%   i.e. [fval,dfdx] = fun(x)
%   or not, i.e. fval = fun(x)
%x_guess the initial guess for Newton's method
%solver_params: a MATLAB struct containing solver settings
%   solver_params.dxmin: terminate early if |x_{i+1}-x_{i}|<dxmin
%   solver_params.ftol: terminate early if |f(x_i)|<ftol
%   solver_params.max_iter: maximum number of iterations allowed
%   solver_params.dxmax: terminate early if |x_{i+1}-x_{i}|>dxmax
%       (meaning that jacobian is probably singular, which is bad)
%   solver_params.numerical_diff: boolean (0 or 1)
%           1-> numerically differentiate, 0-> use analytical derivative
%should use numerical differentation to compute the Jacobian or
%use a Jacobian generated by fun. No input assumes numerical by default
%   true->fun is assumed to return [fval,J]
%   false->fun is assumed to only return fval
%OUTPUTS:
%x: the estimate of the root computed by the function
% exit_flag: an integer indicating whether or not the solver succeeded
%   1: converged (ftol or dxmin met)
%   0: hit max_iter without converging
%  -1: det(J*J') was zero, so the newton step is undefined
%  -2: step was bigger than dxmax (or came out as NaN/Inf)
function [x, exit_flag] = multi_newton_solver(fun,x_guess,solver_params)
    %no struct passed in, so just use all the defaults below
    if nargin < 3
        solver_params = struct();
    end

    %unpack values from struct (if fields in struct have been set)
    dxmin = 1e-14;
    if isfield(solver_params,'dxmin')
        dxmin = solver_params.dxmin;
    end

    ftol = 1e-14;
    if isfield(solver_params,'ftol')
        ftol = solver_params.ftol;
    end

    max_iter = 200;
    if isfield(solver_params,'max_iter')
        max_iter = solver_params.max_iter;
    end

    dxmax = 1e8;
    if isfield(solver_params,'dxmax')
        dxmax = solver_params.dxmax;
    end

    numerical_diff = 1;
    if isfield(solver_params,'numerical_diff')
        numerical_diff = solver_params.numerical_diff;
    end

    exit_flag = 0;
    x = x_guess;

    for n = 1:max_iter
        %get f and J at the current guess
        if numerical_diff
            f_val = fun(x);
            J = approximate_jacobian(fun,x);
        else
            [f_val,J] = fun(x);
        end

        %already close enough to a root, done
        if norm(f_val) < ftol
            exit_flag = 1;
            return;
        end

        %det(J*J') instead of det(J) so this still works with fewer outputs
        %than inputs (J isn't square then). round off means a singular J
        %won't give exactly 0 here, so anything this small counts
        if abs(det(J*J')) < 1e-10
            exit_flag = -1;
            return;
        end

        %newton step, J\f_val does the same thing as inv(J)*f_val
        %without actually inverting J
        dx = -J\f_val;

        %step blew up (J is probably close to singular), bail out
        if ~isfinite(norm(dx)) || norm(dx) > dxmax
            exit_flag = -2;
            return;
        end

        x = x + dx;

        %guess barely moved, done
        if norm(dx) < dxmin
            exit_flag = 1;
            return;
        end
    end
end